repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-docstring-first
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    - id: mypy
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.2.0
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
  - repo: https://github.com/econchick/interrogate
    rev: 1.1.4
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=95]
